In [3]:
pip install opencv-python

  Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [5]:
import cv2
import random 
import numpy as np

In [6]:
# Take the image path
# image_path = "/content/Screenshot (662).png"
image_path = "id.jpg"

In [7]:
print(image_path)

id.jpg


In [8]:
image = cv2.imread(image_path)

In [9]:
print(image)

[[[129 169 174]
  [127 167 172]
  [127 167 172]
  ...
  [162 200 212]
  [163 201 213]
  [163 201 213]]

 [[130 169 178]
  [130 169 178]
  [129 168 177]
  ...
  [161 198 212]
  [162 199 213]
  [163 200 214]]

 [[128 162 185]
  [129 163 186]
  [129 163 186]
  ...
  [161 197 215]
  [162 198 216]
  [163 199 217]]

 ...

 [[161 189 200]
  [164 192 203]
  [164 192 203]
  ...
  [191 219 230]
  [191 219 230]
  [192 220 231]]

 [[165 192 202]
  [164 191 201]
  [161 188 198]
  ...
  [191 219 230]
  [191 219 230]
  [191 219 230]]

 [[163 191 198]
  [161 189 196]
  [160 188 195]
  ...
  [190 218 229]
  [190 218 229]
  [191 219 230]]]


In [11]:
# Display the image
cv2.imshow(image)

error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)


In [7]:
# Convert each pixel range from [0,255] to [0,1]
image = image / 255.0

In [8]:
# print the dimension of the image
dimension = image.shape
print(dimension)

(4000, 3000, 3)


In [9]:
# Print the data type of the image
print(image.dtype)
print(type(image))

float64
<class 'numpy.ndarray'>


In [ ]:
# Generate the keys for the image encryption
mu, sigma = 0, 0.1  # mean and standard deviation
keys = []
for i in range(100):
  key = np.random.normal(mu, sigma, (dimension[0],dimension[1],dimension[2])) + np.finfo(float).eps
  keys.append(key)

In [ ]:
print(len(keys))

In [ ]:
print(keys[0])

In [ ]:
last_key = np.random.randint(0, pow(2, 8)-1, size = dimension, dtype=int)

In [ ]:
print(last_key)

In [ ]:
# Encryption of the image
encrypted_image = image
for i in range(100):
  encrypted_image = encrypted_image/keys[i]

In [ ]:
# Apply the last key on the image
for i in range(dimension[0]):
  for j in range(dimension[1]):

    encrypted_image[i][j][0] = encrypted_image[i][j][0] + last_key[i][j][0]
    if(encrypted_image[i][j][0] > 255):
      encrypted_image[i][j][0] = encrypted_image[i][j][0] - 255 

    encrypted_image[i][j][1] = encrypted_image[i][j][1] + last_key[i][j][1]
    if(encrypted_image[i][j][1] > 255):
      encrypted_image[i][j][1] = encrypted_image[i][j][1] - 255 

    encrypted_image[i][j][2] = encrypted_image[i][j][2] + last_key[i][j][2]
    if(encrypted_image[i][j][2] > 255):
      encrypted_image[i][j][2] = encrypted_image[i][j][2] - 255


In [ ]:
# Print the encrypted image
cv2_imshow(encrypted_image)

In [ ]:
# decryption of the image
decrypted_image = encrypted_image
for i in range(dimension[0]):
  for j in range(dimension[1]):

    decrypted_image[i][j][0] = decrypted_image[i][j][0] - last_key[i][j][0]
    if(decrypted_image[i][j][0] < 0 ):
      decrypted_image[i][j][0] = decrypted_image[i][j][0] + 255 

    decrypted_image[i][j][1] = decrypted_image[i][j][1] - last_key[i][j][1]
    if(decrypted_image[i][j][1] < 0 ):
      decrypted_image[i][j][1] = decrypted_image[i][j][1] + 255

    decrypted_image[i][j][2] = decrypted_image[i][j][2] - last_key[i][j][2]
    if(decrypted_image[i][j][2] < 0 ):
      decrypted_image[i][j][2] = decrypted_image[i][j][2] + 255

In [ ]:
for i in reversed(range(100)):
  decrypted_image = decrypted_image*keys[i]

In [ ]:
# Convert each pixel range from [0,1] to [0,255]  
decrypted_image = decrypted_image*255.0

In [ ]:
# Print the decrypted_image
cv2_imshow(decrypted_image)

In [ ]:
# Comparision between original image and decrypted image
if(decrypted_image.all() == image.all()):
  print("success")